<?php

/**
 * @file
 * Contains ilr.module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
  * Implements hook_form_BASE_FORM_ID_alter().
  */
function ilr_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['saml_login_title'] = [
    '#markup' => '<h2>' . t('Cornell Users') . '</h2>',
    '#weight' => -3
  ];

  $form['saml_login'] = [
    '#type' => 'link',
    '#url' => Url::fromRoute('samlauth.saml_controller_login'),
    '#title' => t('NetID Login'),
    '#weight' => -2,
    '#attributes' => [
      'class' => 'button cu-button'
    ]
  ];

  $form['drupal_login_title'] = [
    '#markup' => '<h2>' . t('No Cornell NetID?') . '</h2>',
    '#weight' => -1
  ];
}

/**
 * Implements hook_entity_view_alter().
 */
function ilr_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->getEntityType()->id() === 'node' && !empty($build['#attached']['html_head_link'])) {
    foreach ($build['#attached']['html_head_link'] as $key => $link) {
      if ($link[0]['rel'] === 'shortlink') {
        unset($build['#attached']['html_head_link'][$key]);
      }
    }
  }
}
