<?php

/**
 * @file
 * Contains ilr.module.
 */

use Drupal\Core\Form\FormStateInterface;
 use Drupal\Core\Url;

/**
  * Implements hook_form_BASE_FORM_ID_alter().
  */
function ilr_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['saml_login_title'] = [
    '#markup' => '<h2>' . t('Cornell Users') . '</h2>',
    '#weight' => -3
  ];

  $form['saml_login'] = [
    '#type' => 'link',
    '#url' => Url::fromRoute('samlauth.saml_controller_login'),
    '#title' => t('NetID Login'),
    '#weight' => -2,
    '#attributes' => [
      'class' => 'button cu-button'
    ]
  ];

  $form['drupal_login_title'] = [
    '#markup' => '<h2>' . t('No Cornell NetID?') . '</h2>',
    '#weight' => -1
  ];

  unset($form['drupal_login_title']);
  unset($form['name']);
  unset($form['pass']);
  unset($form['actions']);
}
